//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.la
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Actemium.Stratus.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using Actemium.Stratus.DataObjects;
    
    public partial class StratusContext : DbContext
    {
        public StratusContext()
            : base("name=StratusContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Plant> Plants { get; set; }
        public virtual DbSet<Zone> Zones { get; set; }
        public virtual DbSet<Cell> Cells { get; set; }
        public virtual DbSet<ProductType> ProductTypes { get; set; }
        public virtual DbSet<Visit> Visits { get; set; }
        public virtual DbSet<SequenceExecution> SequenceExecutions { get; set; }
        public virtual DbSet<Sequence> Sequences { get; set; }
        public virtual DbSet<Result> Results { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<Tester> Testers { get; set; }
        public virtual DbSet<Process> Processes { get; set; }
        public virtual DbSet<ResultDescription> ResultDescriptions { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserClaim> UserClaims { get; set; }
        public virtual DbSet<UserLogin> UserLogins { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
    }
}
