//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Actemium.Stratus.DataObjects
{
     
    using System;
    using System.Collections.Generic;
    
    
    public partial class Cell : IEntity , INamedEntity 
    {
        public Cell()
        {
            this.Visits = new HashSet<Visit>();
            this.Zones = new HashSet<Zone>();
            this.Locations = new HashSet<Location>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Visit> Visits { get; set; }
        public virtual ICollection<Zone> Zones { get; set; }
        public virtual ICollection<Location> Locations { get; set; }
    }
}
