//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Actemium.Stratus.DataObjects
{
    using System;
    
    public enum DataFileType : int
    {
        Hex = 0,
        Text = 1,
        UU31 = 2
    }
}
