//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Actemium.Stratus.DataObjects
{
     
    using System;
    using System.Collections.Generic;
    
    
    public partial class Plant : IEntity , INamedEntity 
    {
        public Plant()
        {
            this.Visits = new HashSet<Visit>();
            this.Companies = new HashSet<Company>();
            this.Testers = new HashSet<Tester>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Visit> Visits { get; set; }
        public virtual ICollection<Company> Companies { get; set; }
        public virtual ICollection<Tester> Testers { get; set; }
    }
}
