//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Actemium.Stratus.DataObjects
{
    using System;
    
    public enum ResultType : int
    {
        Grouped = 5,
        Parent = 8,
        Boolean = 2,
        Operator = 7,
        Numeric = 6,
        Bounded = 3,
        Array = 1,
        String = 9,
        DataFile = 4
    }
}
