//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Actemium.Stratus.DataObjects
{
     
    using System;
    using System.Collections.Generic;
    
    
    public partial class Sequence : IEntity , INamedEntity 
    {
        public Sequence()
        {
            this.SequenceExecutions = new HashSet<SequenceExecution>();
            this.Results = new HashSet<Result>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<SequenceExecution> SequenceExecutions { get; set; }
        public virtual ICollection<Result> Results { get; set; }
    }
}
