//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Actemium.Stratus.DataObjects
{
    using System;
    
    [Flags]
    public enum SequenceStatus : int
    {
        None = 0,
        Pass = 1,
        Fail = 2,
        Aborted = 3,
        Released = 4
    }
}
