//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Actemium.Stratus.DataObjects
{
     
    using System;
    using System.Collections.Generic;
    
    
    public partial class Tester : IEntity , INamedEntity 
    {
        public Tester()
        {
            this.Visits = new HashSet<Visit>();
            this.Plants = new HashSet<Plant>();
            this.Processes = new HashSet<Process>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string TesterDescription { get; set; }
    
        public virtual ICollection<Visit> Visits { get; set; }
        public virtual ICollection<Plant> Plants { get; set; }
        public virtual ICollection<Process> Processes { get; set; }
    }
}
