//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Actemium.Stratus.DataObjects
{
     
    using System;
    using System.Collections.Generic;
    
    
    public partial class Visit : IEntity  
    {
        public Visit()
        {
            this.SequenceExecutions = new HashSet<SequenceExecution>();
        }
    
        public int Id { get; set; }
        public VisitStatus Status { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public int Duration { get; set; }
        public int ProductId { get; set; }
        public int TesterId { get; set; }
        public int ZoneId { get; set; }
        public int CellId { get; set; }
        public int LocationId { get; set; }
        public int ProcessId { get; set; }
        public int PlantId { get; set; }
        public int CompanyId { get; set; }
        public string VisitXml { get; set; }
    
        public virtual ICollection<SequenceExecution> SequenceExecutions { get; set; }
        public virtual Product Product { get; set; }
        public virtual Tester Tester { get; set; }
        public virtual Zone Zone { get; set; }
        public virtual Cell Cell { get; set; }
        public virtual Location Location { get; set; }
        public virtual Process Process { get; set; }
        public virtual Plant Plant { get; set; }
        public virtual Company Company { get; set; }
    }
}
